### ISSUE TITLE
Réglage Spleef récompense 

### ISSUE THREAD

**Issue by SharkblackFr** [xaniox/HeavySpleef#26]
Bonjour,
je voudrais savoir comment régler les récompenses du spleef lorsqu'il y a un gagnant de façon qu'il gagne de l'argent du serveur...

Merci d'avance de votre aide et de votre compréhension

**Comment by xaniox** [comment]
Hey,

since I don't speak French I have to respond in English. To add rewards to a game you have to use different game flags. 

For money rewards you have to add the "reward" flag: /spleef flag <game> reward <reward-1st> <reward-2nd> <etc...>

For item rewards: /spleef flag <game> itemreward.
You can then add multiple item rewards using /spleef flag <game> itemreward:add <item[:data]> [amount]

**Comment by SharkblackFr** [comment]
thank you
