### ISSUE TITLE
feature

### ISSUE THREAD

**Issue by pixar02** [xaniox/HeavySpleef#42]
Could it be possible to add a random join thing ?
So when a player steps on a pressure plate it will join a random game..?

**Comment by xaniox** [comment]
I just wrote a small addon for this: https://xaniox.de/heavyspleef/addons/2.4/addon_RandomJoin.jar

Commands:
/spleef addrandomjoinplate
/spleef removerandomjoinplate

After executing these commands you can click on any pressure plate and it will be added to HeavySpleef. Once a player steps on it, he'll join a random game.

Permissions:
heavyspleef.admin.addrandomjoinplate
heavyspleef.admin.removerandomjoinplate
heavyspleef.player.userandomjoinplate

There is also a new flag shipped, which lets you select a certain leavepoint **only for players, who joined via the pressure plates**. I had to implement this flag since a player will be teleported to his origin location where he joined the game (at default). Thus a player will always be teleported back on to the pressure plate and he'll never be able to escape the "join loop".

Flags:
randomplate-leavepoint

**Comment by pixar02** [comment]
Thank you very much!
Just what I needed

**Comment by xaniox** [comment]
I'm not sure yet if this addon will become an official one, since it's very specific. I'll see what I can do in the next update.
