### ISSUE TITLE
Shovels enabled but don't show up in inventory

### ISSUE THREAD

**Issue by jhkoenig** [xaniox/HeavySpleef#60]
Players enter the arena but don't have any shovels, although shovels are enabled.

**Comment by jhkoenig** [comment]
Seems to work if I set: adventure-mode: false in config.yml

**Comment by xaniox** [comment]
Since a similar issue has already been reported in past, there is a comment above the config option you mentioned stating that setting the option to false may fix strange inventory behaviours.
I'm not 100% sure, but I think that this issue has something to do with the Server/Client themselves.

So if you don't mind the adventure mode you can just leave this option being set to false :)
