### ISSUE TITLE
FAWE + HeavySpleef floor generation problems

### ISSUE THREAD

**Issue by TheoRetisch1** [xaniox/HeavySpleef#65]
If FastAsynchronWorldEdit is running on a server the floor schematic wont load in time. Sometimes it takes serveral minutes, sometimes it doesnt work, sometimes it happens in a running game. There are no erros in the log. Running only default worldedit everything works fine. FastAsnychronWorldedit contains a very huge performance advantage, revolutionary new buidling tools and is used by many server, because of that I would love to see an update adding compatibility. Probably you have to add something like a delay for the floor-schematic-loading. 

FAWE: https://www.spigotmc.org/resources/fast-async-worldedit-voxelsniper.13932/ --> latest version
HeavySpleef: 2.4.1 - b340
PaperSpigiot: 1.12.1 #1191

**Comment by TheoRetisch1** [comment]
The issue is still exist and since its game breaking I would be very grateful for any help you can provide. Here is a link to the FAWE API with an explanation how you can paste a schematic using FAWE: 
https://github.com/boy0001/FastAsyncWorldedit/wiki/Pasting-a-schematic. I suppose this would solve the issue.

**Comment by xaniox** [comment]
Hey, I've implemented a possible fix in the latest development build #341. Could you please test it and tell me if it's working?

I never experienced any issues while having FAWE and HeavySpleef installed at the same time, the floor always regenerated correctly.

BTW: Seems like I can't join your server since glizer thinks that my account has been compromised, which isn't so. Maybe you could add me to the whitelist so I may join your server (IGN: Matze)

**Comment by TheoRetisch1** [comment]
I tested the development build on my testserver and it works like a charm. I added your account to the glizer whitelist. Thank you soo much :).
